<a href="https://colab.research.google.com/github/dumkwufavour/shensen_waste/blob/main/Shensen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import tools

In [2]:
import pandas as pd
import re
import numpy as np

In [6]:
df = pd.read_csv("Shensen Waste.csv")

df.head()

,Aggregator,CollectorName,FirstName,LastName,Email,Gender,State,Location,DisabilityStatus,BaselineIncomeMonthly,...,HasBankAccount,SavesMoneyRegularly,ExperiencedHarassmentOrSafetyConcerns,ChildrenShouldWorkAsCollectors,E.Month,E.Year,Month,Year,Duplicate check,Baseline Cases
0,saddiqan general enterprises,aisha muhammad aliyu,aisha,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
1,saddiqan general enterprises,fatima muhammad aliyu,fatima,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
2,saddiqan general enterprises,rumaisa adam,rumaisa,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
3,saddiqan general enterprises,aisha adam,aisha,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
4,saddiqan general enterprises,zainab aliyu,zainab,aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Aggregator                             1390 non-null   object
 1   CollectorName                          1390 non-null   object
 2   FirstName                              1390 non-null   object
 3   LastName                               1390 non-null   object
 4   Email                                  23 non-null     object
 5   Gender                                 1390 non-null   object
 6   State                                  1390 non-null   object
 7   Location                               1390 non-null   object
 8   DisabilityStatus                       1390 non-null   object
 9   BaselineIncomeMonthly                  1390 non-null   int64
 10  Date                                   1390 non-null   object
 11  Time                                   1390 non-null   object
 12  AgeRange                               1390 non-null   object
 13  Age Groups                             1390 non-null   object
 14  ExistingCollector                      1390 non-null   object
 15  Institution                            1318 non-null   object
 16  EnrollmentDate                         1390 non-null   object
 17  CreatedBy                              1390 non-null   object
 18  Status                                 1390 non-null   object
 19  EnrollmentChannel                      1390 non-null   object
 20  WouldJoinWomenOnlyCluster              1099 non-null   object
 21  ClusterGenderCategory                  425 non-null    object
 22  ClusterName                            420 non-null    object
 23  PartOfCollectionGroup                  1390 non-null   object
 24  EmploymentType                         1390 non-null   object
 25  PlasticCollectedKgPerMonth             1390 non-null   int64
 26  HasBankAccount                         1390 non-null   bool
 27  SavesMoneyRegularly                    1390 non-null   bool
 28  ExperiencedHarassmentOrSafetyConcerns  1390 non-null   object
 29  ChildrenShouldWorkAsCollectors         1390 non-null   object
 30  E.Month                                1390 non-null   int64
 31  E.Year                                 1390 non-null   int64
 32  Month                                  1390 non-null   int64
 33  Year                                   1390 non-null   int64
 34  Duplicate check                        1390 non-null   int64
 35  Baseline Cases                         372 non-null    object
dtypes: bool(2), int64(7), object(27)
memory usage: 372.1+ KB

In [8]:
name_cols = ['FirstName', 'LastName']

In [9]:
#Remove irregular characters from the 'FirstName', 'LastName' and convert all entries in the 'FirstName' column to lowercase for consistency
df[name_cols] = df[name_cols].apply(lambda x: x.astype(str).str.lower().str.replace(r'\s+', ' ', regex=True).str.strip())

# Print a confirmation message to indicate the conversion has taken place
print("Converted 'name_cols' to lowercase.")

# Display the first few rows of the DataFrame to show the updated 'FirstName' column
df.head()

Converted 'name_cols' to lowercase.

,Aggregator,CollectorName,FirstName,LastName,Email,Gender,State,Location,DisabilityStatus,BaselineIncomeMonthly,...,HasBankAccount,SavesMoneyRegularly,ExperiencedHarassmentOrSafetyConcerns,ChildrenShouldWorkAsCollectors,E.Month,E.Year,Month,Year,Duplicate check,Baseline Cases
0,saddiqan general enterprises,aisha muhammad aliyu,aisha,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
1,saddiqan general enterprises,fatima muhammad aliyu,fatima,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
2,saddiqan general enterprises,rumaisa adam,rumaisa,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
3,saddiqan general enterprises,aisha adam,aisha,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
4,saddiqan general enterprises,zainab aliyu,zainab,aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN

## Phone numbers were removed before processing this file for privacy reasons, but you can still read the code to understand how duplicates would've worked.

In [10]:
# subset_cols = name_cols + ['PhoneNumber']

# duplicate_rows = df[df.duplicated(subset=subset_cols, keep=False)]

# if not duplicate_rows.empty:
#     print(f"Found {len(duplicate_rows)} duplicate rows based on {subset_cols}:")
#     print(duplicate_rows[subset_cols])
# else:
#     print(f"No duplicate rows found based on {subset_cols}.")

In [11]:
# # Sort the duplicates so they appear grouped
# duplicate_rows_sorted = duplicate_rows.sort_values(
#     by= name_cols + ['PhoneNumber']
# )

# output_file_path = "duplicate_prep (15th July, 2026).csv"

# # Save the duplicate rows DataFrame to a CSV file
# duplicate_rows_sorted.to_csv(output_file_path, index=False)

# # Print a message confirming that the duplicate rows have been saved and specifying the file path
# print(f"Duplicate rows saved to '{output_file_path}'")

In [12]:
# #Remove irregular characters from the 'FirstName', 'LastName' and convert all entries in the 'FirstName' column to lowercase for consistency
# df["CreatedBy"] = df["CreatedBy"].str.lower().str.replace(r'\s+', ' ', regex=True).str.strip()

# # Print a confirmation message to indicate the conversion has taken place
# print("Converted 'CreatedBy' to lowercase.")

# # Display the first few rows of the DataFrame to show the updated 'FirstName' column
# df.head()

In [13]:
df["CollectorName"] = df["FirstName"] + " " + df["LastName"]

df.head()

,Aggregator,CollectorName,FirstName,LastName,Email,Gender,State,Location,DisabilityStatus,BaselineIncomeMonthly,...,HasBankAccount,SavesMoneyRegularly,ExperiencedHarassmentOrSafetyConcerns,ChildrenShouldWorkAsCollectors,E.Month,E.Year,Month,Year,Duplicate check,Baseline Cases
0,saddiqan general enterprises,aisha muhammad aliyu,aisha,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
1,saddiqan general enterprises,fatima muhammad aliyu,fatima,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
2,saddiqan general enterprises,rumaisa adam,rumaisa,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
3,saddiqan general enterprises,aisha adam,aisha,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
4,saddiqan general enterprises,zainab aliyu,zainab,aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN

In [14]:
cols = df.columns.tolist()

cols.insert(1, cols.pop(cols.index("CollectorName")))

df = df[cols]

In [15]:
df.head()

,Aggregator,CollectorName,FirstName,LastName,Email,Gender,State,Location,DisabilityStatus,BaselineIncomeMonthly,...,HasBankAccount,SavesMoneyRegularly,ExperiencedHarassmentOrSafetyConcerns,ChildrenShouldWorkAsCollectors,E.Month,E.Year,Month,Year,Duplicate check,Baseline Cases
0,saddiqan general enterprises,aisha muhammad aliyu,aisha,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
1,saddiqan general enterprises,fatima muhammad aliyu,fatima,muhammad aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
2,saddiqan general enterprises,rumaisa adam,rumaisa,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
3,saddiqan general enterprises,aisha adam,aisha,adam,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN
4,saddiqan general enterprises,zainab aliyu,zainab,aliyu,NaN,Female,Kano,KUMBOTSO,no,0,...,True,False,No,No,4,2026,5,2026,1,NaN

In [17]:
output_file = "Cleaned Shensen Waste.csv"

df.to_csv(output_file, index=False)

print(f"created and saved data into {output_file}")

created and saved data into Cleaned Shensen Waste.csv

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1390 entries, 0 to 1389
Data columns (total 36 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Aggregator                             1390 non-null   object
 1   CollectorName                          1390 non-null   object
 2   FirstName                              1390 non-null   object
 3   LastName                               1390 non-null   object
 4   Email                                  23 non-null     object
 5   Gender                                 1390 non-null   object
 6   State                                  1390 non-null   object
 7   Location                               1390 non-null   object
 8   DisabilityStatus                       1390 non-null   object
 9   BaselineIncomeMonthly                  1390 non-null   int64
 10  Date                                   1390 non-null   object
 11  Time                                   1390 non-null   object
 12  AgeRange                               1390 non-null   object
 13  Age Groups                             1390 non-null   object
 14  ExistingCollector                      1390 non-null   object
 15  Institution                            1318 non-null   object
 16  EnrollmentDate                         1390 non-null   object
 17  CreatedBy                              1390 non-null   object
 18  Status                                 1390 non-null   object
 19  EnrollmentChannel                      1390 non-null   object
 20  WouldJoinWomenOnlyCluster              1099 non-null   object
 21  ClusterGenderCategory                  425 non-null    object
 22  ClusterName                            420 non-null    object
 23  PartOfCollectionGroup                  1390 non-null   object
 24  EmploymentType                         1390 non-null   object
 25  PlasticCollectedKgPerMonth             1390 non-null   int64
 26  HasBankAccount                         1390 non-null   bool
 27  SavesMoneyRegularly                    1390 non-null   bool
 28  ExperiencedHarassmentOrSafetyConcerns  1390 non-null   object
 29  ChildrenShouldWorkAsCollectors         1390 non-null   object
 30  E.Month                                1390 non-null   int64
 31  E.Year                                 1390 non-null   int64
 32  Month                                  1390 non-null   int64
 33  Year                                   1390 non-null   int64
 34  Duplicate check                        1390 non-null   int64
 35  Baseline Cases                         372 non-null    object
dtypes: bool(2), int64(7), object(27)
memory usage: 372.1+ KB